### PR TITLE
fix #119 and upgrade some js deps

### LINKED ISSUE #119: bug: cancel_all_orders may crash
<https://github.com/Fluidex/dingir-exchange/blob/fb4638dcd0caa6e6176cfea38713d1653e3d4f08/src/message/mod.rs#L58>

<https://github.com/Fluidex/dingir-exchange/blob/fb4638dcd0caa6e6176cfea38713d1653e3d4f08/src/message/mod.rs#L102>

<https://github.com/Fluidex/dingir-exchange/blob/fb4638dcd0caa6e6176cfea38713d1653e3d4f08/src/matchengine/controller.rs#L74>

Imagine this case: a user with lots of orders makes a 'cancel_all' req, then controller checks the message_manager queue and finds the queue is not full. Then in the `cancel_all` function, orders are cancelled one by one, and **each order cancelled will generate a msg into the queue!**, so the the queue inside message_manager will be full and process panics!... 

Maybe we should use unlimited queue and implement is_full as `queue.len() > A_VALUE_IN_CONFIG`

### PR DESCRIPTION
**Pull request by lispc**

### CODE REVIEW

File: src/message/mod.rs [hunk 1]
```diff
@@ -99,8 +99,10 @@ impl<T: producer::MessageScheme> MessageManager for RdProducerStub<T> {
     */
 
     fn is_block(&self) -> bool {
-        self.sender.is_full()
+        // https://github.com/Fluidex/dingir-exchange/issues/119
+        //self.sender.is_full()
         //self.sender.len() >= (self.sender.capacity().unwrap() as f64 * 0.9) as usize
+        self.sender.len() >= (self.sender.capacity().unwrap() - 1000)
```
Comment (HAOYUatHZ) [inline src/message/mod.rs:105]: prefer using the original style (` as f64 * 0.9`  or ` as f64 * 0.5`) here.

Otherwise if we decrease ` let (sender, receiver) = crossbeam_channel::bounded(2048);` to a small number 
and forget to change `self.sender.capacity().unwrap() - 1000`, it may become a negative number

Comment (lispc) [reply src/message/mod.rs:105]: just a temp fix. I will keep #119 open. 
Currently I have to reserve >600 space in the queue due to tick.js
